spring.application.name=bank-system
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_system
spring.datasource.username=postgres
spring.datasource.password=0
spring.jpa.hibernate.ddl-auto=update
server.servlet.session.cookie.same-site=strict